### PR TITLE
pls check

### PR DESCRIPTION
**Pull request by zzmtsvv**
Good evening
I've done it

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alexey.

2.6 The task requires (little remark, but remake it):
Merge arrays to the A (first array). You did 3rd array instead.

2.10 The task requires max including main diagonal (small change).

Everything done well!

**Comment by zzmtsvv** [comment]
2.6 I have to write something like that?

`
a = merge_arrays(remove_idx(a, idx_a), remove_idx(b, idx_b));
`
so the length of the array a will be changed to the appropriate format

if that's it - I've fixed everything

**Comment by zzmtsvv** [comment]
and can I defend this lab on Tuesday?

**Comment by NemirovichMark** [comment]
Hello Alexey.

Yes, such small corrections it is what I asked about (be more attentive to the task)

You can come to class to defend 5rd lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
