### PR TITLE
Update Theory.cs

### PR DESCRIPTION
**Pull request by AleksandrZyuzyukin**
Hello Mark!
I did it.
Could you check it please?

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alexander.

3.4
What's the point? You for each method create a pointer. And call the method by pointer. 
image
You can use delegates in 3 ways I wrote in the Theory (look at the updated file)
You can create 1 pointer and change the method which it point on.

The same with 3.6 & 3.13

1.1 Use a method for better performance. DRY principle - don't repeat yourself
fact(n5, out vern5);
                fact(n10, out vern10);
                fact(k5, out verk5);
                fact(k10, out verk10);
                fact(n5 - k5, out vernk5);
                fact(n10 - k10, out vernk10);
                c5 = vern5 / verk5 / vernk5;
                c10 = vern10 / verk10 / vernk10;

1.2 Instead of so long conditions use check before P calculation for each triangle. Your program have to be able for extension (3, 4 and more triangles). (DRY & SOLID principles (in this case O))
if((a1>0)&&(b1>0)&&(c1>0)&&(a2>0)&&(b2>0)&&(c2>0))
                {
                    if ((a1 + b1 > c1) && (a2 + b2 > c2) && (a1 + c1 > b1) && (a2 + c2 > b2) && (b1 + c1 > a1) && (b2 + c2 > a2))

And one method can calls another!

Actually return value is better than out local variable. Use out, please, only if you have to get more than 1 value (different) from the method.
static void maxx(double[] x, out int indm)
->
static int maxx(double[] x)
 int indm
...
return  indm


Lastly, methods are best written at the same level. Not one in the other (main is a method too)

**Comment by NemirovichMark** [comment]
2.10 Wrong work.
image
image
image

**Comment by AleksandrZyuzyukin** [comment]
Hello Mark!
I hope, I fixed all)
Could you please check it?

**Comment by NemirovichMark** [comment]
Hello Alexandr.

2.10 Wrong. Everything else - good.
image
image

**Comment by AleksandrZyuzyukin** [comment]
Hello Mark!
I found that silly mistake!

**Comment by NemirovichMark** [comment]
It was hilarious enough.

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
