### PR TITLE
Please check :)

### PR DESCRIPTION
**Pull request by Toliyy**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Anatoliy.
1.1 Decompose it, please.
image

1.2 If I want to cxompare 10 triangles, what would you do?
image

**Comment by NemirovichMark** [comment]
2.23 5 elements have to be increased. Others - decreased. Be aware that negative numbers have opposite behaviour comparatelly to positive
image

**Comment by Toliyy** [comment]
I have fixed all errors

**Comment by NemirovichMark** [comment]
Hello Anatoliy.

1.1 Factorial calculation have to be in one method and formula - in another.
image

1.2 Accept

2.23 Better, but not perfect
image

**Comment by Toliyy** [comment]
I have fixed all error

**Comment by Toliyy** [comment]
I have fixed all error 23

**Comment by NemirovichMark** [comment]
All right!

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
