### PR TITLE
Lab 5 is done

### PR DESCRIPTION
**Pull request by NikitaZhukovskiy**
Good morning!
I did my 5 lab. Check it pls

### CODE REVIEW

**Comment by NikitaZhukovskiy** [comment]
After defending the lad I added task 3 (level 3) to my repository

**Comment by NikitaZhukovskiy** [comment]
Good evening!
Do I have mistakes in lab?  I just can't understand if I did everything right or not.

**Comment by NemirovichMark** [comment]
Hello, Nikita. In the process now.

**Comment by NemirovichMark** [comment]
1.2 How can you compare inexisting triangles?
image

2.10 Nope. So I cannot provide 5 to you on these week. You can try next time again (without downgrage)
image

You have to find MIN above diagonal. Be more attentive, which elements in the loop you count. And even your work with 2 MAXs works wrong, you deleted wrong column.

**Comment by NemirovichMark** [comment]
2.23 Crash with negative numbers:
image

**Comment by NemirovichMark** [comment]
For the future:
Name "var" for variable is very bad (because it is base clue word), do not use it, please. (use foo & bar, if you want simple canonic names)

**Comment by NikitaZhukovskiy** [comment]
**Hello, Mark!**
I corrected all mistakes. Check reworked tasks, please.

**Comment by NemirovichMark** [comment]
Hello Nikita.

1.2 👍 

2.10 👍 

2.23 Wrong
image

**Comment by NikitaZhukovskiy** [comment]
I reworked Task 23. Check file "**Final Task 23**".
P.S. "Reworked Level 2 Task 23" was solved incorrectly, so don't check it

**Comment by NemirovichMark** [comment]
Hello Nikita.

Good job!

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
