### PR TITLE
Update Theory.cs

### PR DESCRIPTION
**Pull request by AlinaVedernikova**
Hello, I did evrythyng :)

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alina.

1.2 DRY - don't repeat yourself. Encapsulate input of the triangles to method, please. And then call it for creating 1st & 2nd triangle (tuple or array). It have to be easy add 1 triangle more (1 line instead of 10+).
image

2.23 Only 5 max elements have to be. And -2 > -4. Wrong work with negative numbers
image

Everything else is good 👍

**Comment by AlinaVedernikova** [comment]
Hello! I corrected the solution, but in the 23rd issue I didn’t understand about negative numbers, everything seems to be displayed correctly anyway

**Comment by AlinaVedernikova** [comment]
I fixed 2.23)

**Comment by NemirovichMark** [comment]
Hello Alina.

Perfect!

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
