### PR TITLE
5Lab ready

### PR DESCRIPTION
**Pull request by RomaNazarenko**
Please answer question in Method Task3_2

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Roman.

Read about ?: here:
https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/conditional-operator
**continue** doesn't have return type, it is a command.
Morethen, it is required to save a result (it is not equal to if-else (but very similar) operator)
image

2.10
image
But
image

And you can optimize it:
image

3.2 DRY - don't repeat yourself. There is difference in the method only! And it should be send as delegate (reference to the method you interested in).
if (i % 2 == 0)
                    {
                        double[] temp = new double[Ar.GetLength(1)];
                        for (int j = 0; j != Ar.GetLength(1); j++)
                        {
                            temp[j] = Ar[i, j];
                        }

                        Program Pr = new Program();
                        temp = Pr.Vosrast(temp);

                        for (int j = 0; j != Ar.GetLength(1); j++)
                        {
                            Ar[i, j] = temp[j];
                        }
                    }
                    else
                    {

                        double[] temp = new double[Ar.GetLength(1)];
                        for (int j = 0; j != Ar.GetLength(1); j++)
                        {
                            temp[j] = Ar[i, j];
                        }
                        Program Pr = new Program();
                        temp = Pr.Ybiv(temp);
                        for (int j = 0; j != Ar.GetLength(1); j++)
                        {
                            Ar[i, j] = temp[j];
                        }

                    }

3.6 Use delegate instead:
int k = pr.Diag(Ar);
int j = pr.Perv(Ar);
->
int k = pr.FindMax(Diag, Ar);
int j = pr.FindMax(First, Ar);

**Comment by RomaNazarenko** [comment]
Honestly, I didn't understand what was wrong and so on, but I'd like to
defend tomorrow 3 and 4 lab on 3th lesson and I'll ask you about this
message. Ok?
пн, 31 окт. 2022 г., 14:13 Mark ***@***.***>:

**Comment by NemirovichMark** [comment]
Ok, you are welcome.

**Comment by RomaNazarenko** [comment]
Well. I changed my program, but can't understand with delegate, particularly Task 3.2. Could you me a small example (model) of using delegate, how should i do it in 3.2?

**Comment by NemirovichMark** [comment]
Hello Roman.

Here 3 examples how to use delegates:
https://github.com/NemirovichMark/5th_Lab/blob/master/Theory.cs

**Comment by NemirovichMark** [comment]
More information:
https://www.geeksforgeeks.org/c-sharp-delegates/

**Comment by NemirovichMark** [comment]
I wait for update. You didn't upload it yet:
image

**Comment by RomaNazarenko** [comment]
I'll look through the information about delegates a bit later, so I'll drop
you my updates approximately on Sunday

чт, 3 нояб. 2022 г., 17:11 Mark ***@***.***>:

**Comment by NemirovichMark** [comment]
Ok

**Comment by RomaNazarenko** [comment]
Well, I updated my program. Check it pls. I believe I'm right

**Comment by NemirovichMark** [comment]
Good!

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
