### PR TITLE
5th lab

### PR DESCRIPTION
**Pull request by StepanTsepilov**

### CODE REVIEW

**Comment by StepanTsepilov** [comment]
Почему в таблице с прогрессом у меня стоит допуск к защите 3 лабы? Я на прошлой практике защитил ее

**Comment by NemirovichMark** [comment]
Hello.

I could miss it. Let me check. And what number you did on the defend?

**Comment by StepanTsepilov** [comment]
3.10

**Comment by NemirovichMark** [comment]
Fixed.
Your solution of the 5th lab I will check later.

**Comment by NemirovichMark** [comment]
Hello Stepan.

static void Fact(int z, out double fz)
- better to use return instead of out:
static double Fact(int z)
double fz =
...
return fz

do not use general names:
MatrixWork

How understand what is it?
static double[] sw(fx f, double[] Array)
    {
        return f(Array);
    }

static double[] f1(double[] x)
    {
        Array.Sort(x);
        return x;
    }
    static double[] f2(double[] x)
    {
        Array.Sort(x);
        Array.Reverse(x);
        return x;
    }

Rename it to normal, please. It is too consuming (by time) to read (jump) it.

**Comment by NemirovichMark** [comment]
Thank you!
It much more readable now!
1.2
image

2.6
image

2.10 For negative, zero & one:
image

**Comment by NemirovichMark** [comment]
Good job Stepan,

You can come to class to defend 5rd lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
