### PR TITLE
Create 5-th lab

### PR DESCRIPTION
**Pull request by Mihail-Shalyrin**

### CODE REVIEW

**Comment by Mihail-Shalyrin** [comment]
Check pls

**Comment by NemirovichMark** [comment]
Hello Mikhail.

Seems, it is not full work:
image

If you wrote it in the different projects, please upload them as separate documents.
It is very difficult to check your work now.
image

**Comment by Mihail-Shalyrin** [comment]
ll

**Comment by NemirovichMark** [comment]
Hello Mikhail.

1.2 Why do you use 2 similar methods? Use one. And call it twice. And do not compare an impossible triangles, please.
image

2.10 Wrong when min & max in the one column
image

2.23 program have to be universal. Not only with size = 5. Do not use "magic numbers". Use variables or constant instead.
image

Everything else done well.

**Comment by Mihail-Shalyrin** [comment]
Check my cration pls

**Comment by NemirovichMark** [comment]
Hello Makhail.

1.2 👍 

2.10 Still wrong when max & min in one column. Only that column have to be deleted.
image
Seems, I know, why: upper triandle have to start from 2nd column!
image

2.23 In the task doesn't asked to sort matrix. Please, do not (or don't show) what didn't required. And it is work wrong with negative numbers.
image

**Comment by Mihail-Shalyrin** [comment]
l

**Comment by NemirovichMark** [comment]
Hello Mikhail.

Did you delete your solution intentionally? 
Let me know, when you would upload it again.

**Pull request closed without merging**
