### PR TITLE
finally lab 5

### PR DESCRIPTION
**Pull request by zitaisan**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Taisia.

2.10 If Min & Max in one column, only 1 column have to be deleted!
image

2.23 Only 5 elements are max. And -2 < -4.
image

Everything else is correct 👍

**Comment by NemirovichMark** [comment]
2.10 right 👍 

2.23 in a process

**Comment by zitaisan** [comment]
check;(

**Comment by NemirovichMark** [comment]
Hello Taisia.

2.23 Only 5 elements have to be increased!
image

Fix remarks till the Tuesday. Otherwise the mark for defence will be erased.

**Comment by zitaisan** [comment]
hope, that 23 is true... please, check:/

**Comment by NemirovichMark** [comment]
Hello Taisia.

Yes, the devil hides in the little things.
So, you are free (with 5). 

You can come to class to defend 5th lab. (**already did**)
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
