### PR TITLE
Create My_5th_Lab

### PR DESCRIPTION
**Pull request by KovalyukYliana**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Yliana.

You can create less long constructions
image
since result the same
image
or use return instead
image


1.2 InvalidInputValue (when an impossible triangle sended 1 4 99)
image

2.10 IndexOutORange
image

2.23 Only 5 numbers have to be increased. And wrong work with negative numbers. -2 > -4
image

And, please KISS - keep it simple, student. Do not create such terrible things.
image

**Comment by NemirovichMark** [comment]
Hello Yliana.

1.2 👍 
2.10 👍

2.23 Wrong answer when numbers are negative. 
image

Find5max now is better 👍

**Comment by KovalyukYliana** [comment]
I accidentally deleted the previous file.. But I corrected task 2.23 and attached it, you can check it
I hope you will allow me to defend tomorrow on the first pair :)

**Comment by NemirovichMark** [comment]
It is correct now 👍 

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
