### PR TITLE
Lab5

### PR DESCRIPTION
**Pull request by SamikovaElena**
Hello, this is Task For Lab5

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Elena.

2.10 Wrong
image
image

2.23
image
image

Wrong with negative.
-2 > -4

3.6 Do you use delegate here? (nope)
image

**Comment by SamikovaElena** [comment]
Hello, I fixed Lab5

**Comment by NemirovichMark** [comment]
Hello Elena.

((i > j) || (i == j))) can be written as (i >= j)

2.10 👍 

2.23 Almost
image
image

3.6 👍

**Comment by SamikovaElena** [comment]
Update

**Comment by NemirovichMark** [comment]
Good small change)

You can come to class to defend 5th lab. (already did)
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
