### PR TITLE
hello,5lb

### PR DESCRIPTION
**Pull request by Alexey-Khviatskovich**

### CODE REVIEW

**Comment by Alexey-Khviatskovich** [comment]
2_23 вроде всё верно
-1 -2 -3 -4 -5  ---максимальные из -1 -2 -3 -4 -5 -6 -7 -8 -9

**Comment by Alexey-Khviatskovich** [comment]
они умножены на 2, остальные разделены на 2

**Comment by NemirovichMark** [comment]
-1 > -2

-2 > -4

in your case
-2 -> -4 means that it incresed. But -4 < -2

**Comment by NemirovichMark** [comment]
The one of main things of mathods - separate program for parts that will do one small thing.

For example in 1.2 you can move it:
if  (!(a_1 < b_1+c_1 && a_2 < b_2+c_2&& b_1< a_1+c_1 && b_2<a_2+c_2&&c_1<a_1 + b_1 && c_2 < a_2 + b_2))
                {
                    Console.WriteLine("input error");
                    return;
                }
into Geron method or create a new method CheckTriangle(a,b,c).
I will explain it in the class on this week. But you can leave it now, or change for your better futher work (and getting good habit)

2.23 Read the explanation in the previous message.
You can use flag as a parameter of the method or different methods for positive and negative numbers.

**Comment by NemirovichMark** [comment]
Hello Alexey.

Better.
But this one:
static bool chek_triangle(double a_1,double a_2,double b_1, double c_1, double c_2, double b_2)
            {
                if (!(a_1 < b_1 + c_1 && a_2 < b_2 + c_2 && b_1 < a_1 + c_1 && b_2 < a_2 + c_2 && c_1 < a_1 + b_1 && c_2 < a_2 + b_2))
                {
                    Console.WriteLine("input error");
                    return false;
                }
                return true;
            }//fixed

What if I with to input 5 triangles? Also, try to minimize amount of parameters. You can either use array for common numbers, or (better) to use a scheme for 1 triangle and than call it:

static bool chek_triangle(double a_1, double b_1, double c_1)
            {
                if (!(a_1 < b_1 + c_1 &&  < a_1 + c_1 && c_1 < a_1 + b_1))
...

chek_triangle(a,b,c);
chek_triangle(h,k,l);

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
