### PR TITLE
5-st lab 23 and 10 th tasks

### PR DESCRIPTION
**Pull request by Mihail-Shalyrin**

### CODE REVIEW

**Comment by Mihail-Shalyrin** [comment]
check pls

**Comment by Mihail-Shalyrin** [comment]
i'am closed last repository because its dosnt works correctly

**Comment by NemirovichMark** [comment]
Hello Mikhail.

2.10 Wrong output:
image

2.23 Only 5 max elements have to increses.
image

**Comment by Mihail-Shalyrin** [comment]
lll

**Comment by NemirovichMark** [comment]
2.23 Works right now. But do not use 3-nested loop, please.
image

2.10 👍

**Comment by Mihail-Shalyrin** [comment]
its mean that i have to fixed 2.23 or all well done?

**Comment by Mihail-Shalyrin** [comment]
mean"s***

**Comment by Mihail-Shalyrin** [comment]
if i must to fixed i send a file

**Comment by NemirovichMark** [comment]
Right!

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
