### PR TITLE
lab5

### PR DESCRIPTION
**Pull request by dkarasevgthub**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Dmitriy.

1.1 Factorial of negative number is impossible
1.2 Be careful with a string.Split(); 
And do not try to compare impossible triabgles. Say to used, that he(she) wrote a delirium ;)
image
image

2.6 Doesn't work correctly
image

2.10 Why does the input error?
image
image

2.23 The same
image

3.2 Use only 1 delegate entity. And change the method it reffers in the if-block statement. Call only 1 time.
image

3.6 The same. No need to create a one deledate entity for 1 method. It is like to create a lable that it is "right hand" and another - "left hand" stick them to hands and when you listed "right hand" you seek lable with such name and rise a hand.
Tha pointer have to change the object it's point on. That's have a sence. In your case it is the same as call methods directly.
image

**Comment by dkarasevgthub** [comment]
Solution updated!

**Comment by NemirovichMark** [comment]
Hello Dmitriy.

2.23 Wrong work with negative numbers.
image

Everything else is correct 👍 

Fix remarks till the Tuesday. Otherwise the mark for defence will be erased.

**Comment by NemirovichMark** [comment]
Good.

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
