### PR TITLE
5th Lab

### PR DESCRIPTION
**Pull request by AnastasiyaButskaya**
Hello, Mark.

I did everything!

Could you give me pass to 5th Lab work, please?

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Anastasiya.

#region 5.1.2 - make a check before P calculation, please (10 1 2 - impossible triangle, 0 -1 -2 - too)

#region 5.2.10 Wrong answers
image
image

#region 5.2.23 It works wrong with negative numbers
-2 > -4
image

Everything else is correct 👍

**Comment by AnastasiyaButskaya** [comment]
Hello, Mark.

I solved the problems in 5.2s and 5.1.2

Could you give me pass to 5th Lab work, please?

**Comment by NemirovichMark** [comment]
Hello Anastasiya.

Almost right:
2.23
image

Everything else is good!

**Comment by AnastasiyaButskaya** [comment]
Hello, Mark.

I solved the problem in 5.23!

Could you give me pass to 5th Lab work, please?

**Comment by AnastasiyaButskaya** [comment]
the last variant is a bit better...

**Comment by NemirovichMark** [comment]
Good!

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
