### PR TITLE
lab5

### PR DESCRIPTION
**Pull request by lxncort**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Maria.

1.1 Decomposite it, please. To the method with formula and factorial.
image

2.23 Wrong work with negative numbers. -2 > -4.
image

3.2 Use 1 entity of the delegate.
image

Everything else is correct 👍

**Comment by lxncort** [comment]
i fixed

**Comment by NemirovichMark** [comment]
Hello Maria.

1.1 👍 
2.23 Negative numbers increases when they become closer to zero.
image

3.2 Now it is 2 same lines. What the sence then? I ment that in the if-else block you create a reference for the delegate entity and after that call the method with a delegate as a parameter!
image

**Comment by lxncort** [comment]
I fixed<3

**Comment by NemirovichMark** [comment]
Hello Maria.

2.23 Do not use 3-nested (and more) loops, please. Although it woks right now!
image

3.2 👍

**Comment by lxncort** [comment]
i fixed<3

**Comment by NemirovichMark** [comment]
Better solution is to transform it to array and seeks values and indexes, but okay, I accept it.

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
