### PR TITLE
It's done

### PR DESCRIPTION
**Pull request by dmitryakimov2206283**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Dmitriy.

1.2 Wrong answer (when creats an impossible triangle)
image

2.6 Advice for the future:
Method have to do small job. And very precise job. Your method ArrayUnite have to get 2 arrays and merge them to 1. And send it.
image
These methods are better to call from main. Unite method have to only unite. Hope, you understand my idea.

2.23 Have to work with negative numbers in a right way.
-2 > -4
image

And no need to sort it, actually.

Everything else is right.

**Comment by dmitryakimov2206283** [comment]
Perhabs, I didn't quite understand the task 2.23. I tried doing it myself in excel and I've got the same result as in my program. 
image

I agree, that sorting might make an output a bit confusing and tricky to understand. It was added to algorithm to make it easier.

What I mean by *easier*, is that we have to process matrix through loops only twice. The first loop will sort matrix and the second one will change elements (double them or divide by 2). And we can easily recognize first five maximums of matrix.

Approach without ordering elements seems to me a bit inefficient, because to find five maximums we have to perform five loops.

**Comment by NemirovichMark** [comment]
Good morning.

I didn't say that you have to remove sort. If is it more suitable for you to work with sorted matrix, you can sort it.

In the excel you didn't increse max negative (by value) elements. You increased their abs value, but signed became less. Understood? The same with decreasing:
image

Example:
[ 0 -2 -4
-6 -8 -10
-12 -14 -16]
result:
[0 -1 -2
-3 -4 -20
-24 -28 -32]

**Comment by NemirovichMark** [comment]
Good job Dmitry.

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
