### PR TITLE
Update Theory.cs

### PR DESCRIPTION
**Pull request by PavelNaumkin**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Pavel.

It is awful for reader such style. Please, write the body of the method under the **signature** 
image

1.2 The app is hang up after input of negative number. It is not how good program have to work. Fit it, please.
image

2.6 If input enter, eternal mistake occures.
image

If min & max in one column, only that column have to be deleted!
image

2.23 Why?
image
image

Part 3 is good 👍

**Comment by NemirovichMark** [comment]
Hello Pavel.

2.23 Crash. Fix it, please till the Tuesday. Otherwise, your defend will be erased.
image

Everythinge else is correct 👍

**Comment by NemirovichMark** [comment]
Hello Pavel.

Fix remarks till the Tuesday. Otherwise the mark for defence will be erased.

**Comment by NemirovichMark** [comment]
Hello Pavel.

Nope. -2 > -4. So when you have to decrease negative values you have to make them further from the zero.
image

**Comment by PavelNaumkin** [comment]
I rebuilt method Reconstructing_Matrix by adding if-block, but I thought reducing by 2 times means multiplying by 1/2

**Comment by NemirovichMark** [comment]
Hello.

5 elements have to be increased by 2. Other - decreased. Increasing of positive - multiply, negative - division (by 2).
image


The defend is erased :(

**Comment by PavelNaumkin** [comment]
Good morning. Today I am absent at university beacause of military office, so I wont be able to defend my lab again. What can I do?

**Comment by NemirovichMark** [comment]
Hello.

I undestand you, so I give you 5.

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
