### PR TITLE
Lab5

### PR DESCRIPTION
**Pull request by PokotiloAndrey**
Hello.I done lab 5. Please check it when it's convenient for you.

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Andrey.

2.10 IndexOutOfRange
image

2.23 Do not use 3-nested loops, please
image
image

And it works wrong:
image

3.2 In that case use delegate as pointer to several methods, please. And DRY - don't repeat youself.
image

3.3 DRY - don't repeat youself.
image

3.4 DRY - don't repeat youself.
image

**Comment by PokotiloAndrey** [comment]
Hello again.I fixed mistakes and uploaded new file. Check it plz.

**Comment by NemirovichMark** [comment]
Good afternoon.

2.23 Better. But wrong work with negative numbers. And do not use 3-nested loops!
image
image

Everything else is good 👍

**Comment by PokotiloAndrey** [comment]
Hello. I fixed this mistakes. Now i guess there are no any issues.

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
