### PR TITLE
Update Theory.cs

### PR DESCRIPTION
**Pull request by BALASHOVALEX**
Hello!!! I am ready for your criticism

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alexey.

No need to use 2 delegate's samples. Use only 1 please, and select which method it points in the program.
Matrix Increasing = chet;
Matrix Decreasing = nechet;

Program Pr = new Program(); - Do not create an example of the class inside this class. It breaks dependance between objects.
temp = Pr.Increasing(temp);

#region Task3_3 The same
        delegate double[] vector(double[] a);
        vector less = lesss;
        vector more = moreee;
us esomething like
vector pointer;
...
if() pointer = lesss;
else pointer = moreee;

1.1 DRY - don't repeat yourself. Use method for factorial's calculation.
for (int i = 2; i <= n; i++)
                    numerator *= i;
                for (int i = 2; i <= n - k; i++)
                    denominator1 *= i;
                for (int i = 2; i <= k; i++)
                    denominator *= i;

2.23 Do not return the refference type. You already changed the value of it inside method.
static double[,] sol2_23(double[,] c, double[] max)
return c;

Do not use "magic numbers". Better send it as a parameter. Method have to be maxumum universal.
else if(p < 5)

And it have to work right with negative numbers:
increase (for 5 highest): -1 -> -0.5; -2 -> -1;
decrease (others): -4 -> -8; -9 -> -18;
image

**Comment by NemirovichMark** [comment]
Hello Alexey.

1.1 I meant do not use 3 loops. Calll the method with a loop inside. You removed neccessory element.

2.23 Do not return refference variable (as a method). It is already changed (in your cese)

But works right now.

3 level.
Do you understand how delegates works in your program?
image

Please, use delegates not as a simple pointer to the method.

**Comment by BALASHOVALEX** [comment]
I am Alexander
 
 
--
Александр Балашов
Отправлено из Почты  Mail.ru

**Comment by BALASHOVALEX** [comment]
I didn't understand what I need to change in 2.23 and how to use delegates, drop a link to some material about delegates, please
 
 
--
Александр Балашов
Отправлено из Почты  Mail.ru

**Comment by NemirovichMark** [comment]
Hello Aleksander.
Sorry for my mistake.

I updated the theory file here:
https://github.com/NemirovichMark/5th_Lab/blob/master/Theory.cs
It shows 3 examples.

Official doc:
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/using-delegates

Samples here:
https://www.tutorialsteacher.com/csharp/csharp-delegates

**Comment by NemirovichMark** [comment]
Hello Alexander.

2.23 Do not use more than 2-nested loop.
image

And no need in ref modificator:
image

But now it works right!


About delegates. Look for example and apply it to another your solution.

Work chet1 = new(chet);
                Work nechet1 = new(nechet);
                for (int i = 0; i < a.GetLength(0); i++)
                {
                    if (i % 2 == 0)
                    {
                        double[] temp = new double[a.GetLength(1)];
                        for (int j = 0; j < a.GetLength(0); j++)
                            temp[j] = a[i, j];
                        temp = chet1(temp);
                        for (int j = 0; j < a.GetLength(0); j++)
                            a[i, j] = temp[j];
                    }
                    else
                    {
                        double[] temp = new double[a.GetLength(1)];
                        for (int j = 0; j < a.GetLength(0); j++)
                            temp[j] = a[i, j];
                        temp = nechet1(temp);
                        for (int j = 0; j < a.GetLength(0); j++)
                            a[i, j] = temp[j];
                    }
                }
                return a;

transforms to

Work howToWork;
for (int i = 0; i < a.GetLength(0); i++)
                {
		    double[] temp = new double[a.GetLength(1)];
                        for (int j = 0; j < a.GetLength(0); j++)
                            temp[j] = a[i, j];
                    if (i % 2 == 0)
                    {                        
                        howToWork = chet1;
                    }
                    else
                    {
                        howToWork = nechet;
                    }
			temp = nechet1(temp);
                        for (int j = 0; j < a.GetLength(0); j++)
                            a[i, j] = temp[j];
                }
                return a;

**Comment by NemirovichMark** [comment]
Excellent! 👍 

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
