### PR TITLE
Lab 5

### PR DESCRIPTION
**Pull request by alina-kramarenko**
Hello. I made a part of the lab, please check it out. I'll send the rest tonight.

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello, Alina. Ok.

1.1 👍 
1.2 Your program have not to compare impossible triangles. (1 2 99) or (-88 -5 3)
2.6 👍 
2.10 If min & max in one column, only 1 column have to be deleted.
image

**Comment by alina-kramarenko** [comment]
Hello!
I fixed the errors and attached the rest of the tasks.

**Comment by NemirovichMark** [comment]
Hello.

1.2 DRY - don't repeat yourself.
image

2.10 InvalidInputValue
image

And doesn't work
image

Everything else is correct 👍

**Comment by NemirovichMark** [comment]
Good.
You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
