### PR TITLE
Lab_5

### PR DESCRIPTION
**Pull request by PankovDaniil**

### CODE REVIEW

**Comment by PankovDaniil** [comment]
2.23 My missplay with int and double, but it's working ^_^

**Comment by NemirovichMark** [comment]
Hello Daniil.

1.2 Your program try to calculate an impossible triangles.
image

2.23 Only 5 elements have to be increased.
image

Everything else is correct 👍

**Comment by PankovDaniil** [comment]
1.2 Fixed

**Comment by PankovDaniil** [comment]
2.23 fixed

**Comment by NemirovichMark** [comment]
Hello.

1.2 Good. But better to make a check inside the method. Because, if I'd like to compare 4 trianges, you add 6 conditions more? And if I'd like to compate 10 triangles???
image

2.23 Only 5 max elements have to be increased. Even if they are negative.
image

**Comment by PankovDaniil** [comment]
Сorrect mistakes

**Comment by NemirovichMark** [comment]
Strange order, but it works. Okay.
image

You can come to class to defend 5th lab.
In the class I will ask you about delegate and signature, so prepeares.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/6th_Lab

**Pull request merged**
